### ISSUE TITLE
Result for running vectorfield_inverse_obstacle.py is an all black figure

### ISSUE THREAD

**Issue by aniri15** [hubernikus/dynamic_obstacle_avoidance#11]
Hello,
I tried to running vectorfield_inverse_obstacle.py and other file named after vectorfield in folder example, but I got an all black figure every time, but the running result for animation_moving_obstacle is fine.
What is expected result for, for example, vectorfield_inverse_obstacle.py?
Thanks in advance.

**Comment by hubernikus** [comment]
The result of the `vectorfield_inverse_obstacle.py` looks like this:
![image](https://github.com/user-attachments/assets/a7928a52-4ad6-4b4a-b786-ca279311edc8)

Make sure that you use an interactive python shell (ipython is quite good for that), or save the picture programmatically such that it exists. Or set a breakpoint at the end of the program. Otherwise, it will close before you see it.
